---
title: "Dcurran3_11"
output:
  word_document: default
  html_document: default
date: "2022-11-17"
---

Objective Function

775x1 + 800x2 + 800x3 + 800x4 + 800x5 + 775x6 + 750x7 = MINIMIZE

where:

x1 = Workers Shift 1 (off Sun/Mon)
x2 = Workers Shift 2 (off Mon/Tue)
x3 = Workers Shift 3 (off Tue/Wed)
x4 = Workers Shift 4 (off Wed/Thur)
x5 = Workers Shift 5 (off Thur/Fri)
x6 = Workers Shift 6 (off Fri/Sun)
x7 = Workers Shift 7 (off Sat/Sun)

subject to:

Constraints

x2 + x3 + x4 + x5 + x6 >= 18 (Sun)
x3 + x4 + x5 + x6 + x7 >= 27 (Mon)
x1 + x4 + x5 + x6 + x7 >= 22 (Tues)
x1 + x2 + x5 + x6 + x7 >= 26 (Wed)
x1 + x2 + x3 + x6 + x7 >= 25 (Thu)
x1 + x2 + x3 + x4 + x7 >= 21 (Fri)
x1 + x2 + x3 + x4 + x5 >= 19 (Sat)
 
```{r}
library(lpSolveAPI)
lprec <- make.lp(0, 7)
set.objfn(lprec, c(775, 800, 800, 800, 800, 775, 750))
lp.control(lprec, sense = 'min')

add.constraint(lprec, c(0,1,1,1,1,1,0), ">=", 18)
add.constraint(lprec, c(0,0,1,1,1,1,1), ">=", 27)
add.constraint(lprec, c(1,0,0,1,1,1,1), ">=", 22)
add.constraint(lprec, c(1,1,0,0,1,1,1), ">=", 26)
add.constraint(lprec, c(1,1,1,0,0,1,1), ">=", 25)
add.constraint(lprec, c(1,1,1,1,0,0,1), ">=", 21)
add.constraint(lprec, c(1,1,1,1,1,0,0), ">=", 19)

solve(lprec)
get.objective(lprec)
get.variables(lprec)
```
x1 = 1.33
x2 = 4
x3 = 6.33
x4 = 0
x5 = 7.33
x6 = .33
x7 = 13

x1 = 2  Shift 1
x2 = 4  Shift 2
x3 = 7  Shift 3
x4 = 0  Shift 4
x5 = 8  Shift 5
x6 = 1  Shift 6
x7 = 13 Shift 7


We will want to employ 35 workers. As a quick check to above, we can look at shift 1 (employees off Sunday and Monday). On shift one there are two employees off so we need 33 shifts covered. We see that Sunday needs a minimum of 18 so we are safe to have 2 on shift 1. This logic can be applied to the other days and we will find that we have met the minimum staffing needs for each day. 

With this schedule plan, we will have a minimum cost of $25,175.
 

 
 